# coding: utf-8
from sqlalchemy import Column, Date, DateTime, Enum, Float, Index, Integer, String, Text, text
from sqlalchemy.ext.declarative import declarative_base


Base = declarative_base()
metadata = Base.metadata


class Comm(Base):
    __tablename__ = 'comm'

    uid = Column(Integer, primary_key=True)
    stamp_update = Column(DateTime, nullable=False, server_default=text("'2000-01-01 00:00:00'"))
    stamp_insert = Column(DateTime, nullable=False, server_default=text("'2000-01-01 00:00:00'"))
    comment_user = Column(String)
    comment_internal = Column(String)
    user_group_uid = Column(Integer, index=True, server_default=text("'-1'"))
    user_uid = Column(Integer, index=True, server_default=text("'-1'"))
    order_uid = Column(Integer, index=True, server_default=text("'-1'"))
    sample_uid = Column(Integer, index=True, server_default=text("'-1'"))
    user_sample_name = Column(String(250))
    user_sample_name_modified = Column(String(250))
    sampling_date = Column(Date)
    source_keywords = Column(String(250))
    sample_description = Column(Text)
    run_uid = Column(Integer, index=True, server_default=text("'-1'"))
    machine_id = Column(Integer, server_default=text("'-1'"))
    gene = Column(String(250), index=True, server_default=text("'N/A'"))
    target_taxon = Column(String(250), server_default=text("'N/A'"))
    primer_for = Column(String(100))
    primer_rev = Column(String(100))
    barcode = Column(String(100))
    linker_for = Column(String(100))
    linker_rev = Column(String(100))
    n_reads = Column(Integer, server_default=text("'-1'"))
    min_len = Column(Integer, server_default=text("'-1'"))
    max_len = Column(Integer, server_default=text("'-1'"))
    average_len = Column(Float(asdecimal=True), server_default=text("'-1'"))
    n_phylotypes = Column(Integer, server_default=text("'-1'"))
    country = Column(String(250))
    coord_NS = Column(String(100))
    coord_EW = Column(String(100))
    n_reads_sort = Column(Integer, server_default=text("'-1'"))
    average_len_sort = Column(Float(asdecimal=True), server_default=text("'-1'"))
    n_reads_for = Column(Integer, server_default=text("'-1'"))
    n_reads_rev = Column(Integer, server_default=text("'-1'"))
    n_reads_short = Column(Integer, server_default=text("'-1'"))
    n_reads_low_qual = Column(Integer, server_default=text("'-1'"))
    n_reads_drop_primer = Column(Integer, server_default=text("'-1'"))
    n_reads_both = Column(Integer, server_default=text("'-1'"))
    n_reads_blast_drop = Column(Integer, server_default=text("'-1'"))
    n_reads_hmm_drop = Column(Integer, server_default=text("'-1'"))
    n_chimera = Column(Integer, server_default=text("'-1'"))
    n_contig_0 = Column(Integer, server_default=text("'-1'"))
    comm_struct = Column(String)
    length_stat = Column(String)
    db_gene = Column(String(200))
    db_ver = Column(String(200))
    db_taxon = Column(String(200))
    b_read_sort_done = Column(Integer, server_default=text("'-1'"))
    b_primer_drop_done = Column(Integer, server_default=text("'-1'"))
    b_blast_drop_done = Column(Integer, server_default=text("'-1'"))
    b_hmm_drop_done = Column(Integer, server_default=text("'-1'"))
    b_read_done = Column(Integer, server_default=text("'-1'"))
    b_contig_0_done = Column(Integer, server_default=text("'-1'"))
    b_cm_done = Column(Integer, server_default=text("'-1'"))
    b_community_done = Column(Integer, server_default=text("'-1'"))
    b_contig_0_zip_done = Column(Integer, server_default=text("'-1'"))
    b_sff_done = Column(Integer, server_default=text("'-1'"))
    cdhit_otu = Column(Integer, server_default=text("'-1'"))
    cdhit_stat = Column(Text)
    cdhit_rf = Column(String)
    cdhit_singleton = Column(Integer, server_default=text("'-1'"))
    cdhit_chao = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_chao = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_chao_target = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_chao_lci_target = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_chao_hci_target = Column(Float(asdecimal=True), server_default=text("'-1'"))
    cdhit_chao_lci = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_chao_lci = Column(Float(asdecimal=True), server_default=text("'-1'"))
    cdhit_chao_hci = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_chao_hci = Column(Float(asdecimal=True), server_default=text("'-1'"))
    cdhit_ace = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_ace = Column(Float(asdecimal=True), server_default=text("'-1'"))
    cdhit_ace_lci = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_ace_lci = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_ace_target = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_ace_hci_target = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_ace_lci_target = Column(Float(asdecimal=True), server_default=text("'-1'"))
    cdhit_ace_hci = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_ace_hci = Column(Float(asdecimal=True), server_default=text("'-1'"))
    cdhit_jackknife = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_jackknife = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_jackknife_target = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_jackknife_lci_target = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_jackknife_hci_target = Column(Float(asdecimal=True), server_default=text("'-1'"))
    share_user_group = Column(String(50))
    share_user_uid = Column(String(500))
    cdhit_jackknife_lci = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_jackknife_lci = Column(Float(asdecimal=True), server_default=text("'-1'"))
    cdhit_jackknife_hci = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_jackknife_hci = Column(Float(asdecimal=True), server_default=text("'-1'"))
    cdhit_shannon = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_shannon = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_npshannon_target = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_simpson_target = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_simpson_lci_target = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_simpson_hci_target = Column(Float(asdecimal=True), server_default=text("'-1'"))
    cdhit_shannon_lci = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_shannon_lci = Column(Float(asdecimal=True), server_default=text("'-1'"))
    cdhit_shannon_hci = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_shannon_hci = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_shannon_target = Column(Float(asdecimal=True), server_default=text("'-1'"))
    cdhit_npshannon = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_shannon_hci_target = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_shannon_lci_target = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_npshannon = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_rf_target = Column(String)
    cdhit_simpson = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_simpson = Column(Float(asdecimal=True), server_default=text("'-1'"))
    cdhit_simpson_lci = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_simpson_lci = Column(Float(asdecimal=True), server_default=text("'-1'"))
    cdhit_simpson_hci = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_simpson_hci = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_otu = Column(Integer, server_default=text("'-1'"))
    blast_rf = Column(String)
    phylum_comp = Column(String(255))
    altitude = Column(Float(asdecimal=True), server_default=text("'0'"))
    reference = Column(String(250))
    gb_acc = Column(String(50))
    coord_NS_type = Column(String(1), server_default=text("'N'"))
    coord_EW_type = Column(String(1), server_default=text("'E'"))
    roche_mid = Column(String(20))
    cdhit_otu_target = Column(Integer)
    cdhit_chao_target = Column(Float(asdecimal=True))
    cdhit_rf_target = Column(String)
    cdhit_singleton_target = Column(Integer)
    cdhit_chao_lci_target = Column(Float(asdecimal=True))
    cdhit_chao_hci_target = Column(Float(asdecimal=True))
    cdhit_ace_target = Column(Float(asdecimal=True))
    cdhit_ace_lci_target = Column(Float(asdecimal=True))
    cdhit_ace_hci_target = Column(Float(asdecimal=True))
    cdhit_jackknife_target = Column(Float(asdecimal=True))
    cdhit_jackknife_lci_target = Column(Float(asdecimal=True))
    cdhit_jackknife_hci_target = Column(Float(asdecimal=True))
    cdhit_npshannon_target = Column(Float(asdecimal=True))
    cdhit_shannon_target = Column(Float(asdecimal=True))
    cdhit_shannon_lci_target = Column(Float(asdecimal=True))
    cdhit_shannon_hci_target = Column(Float(asdecimal=True))
    cdhit_simpson_target = Column(Float(asdecimal=True))
    cdhit_simpson_lci_target = Column(Float(asdecimal=True))
    cdhit_simpson_hci_target = Column(Float(asdecimal=True))
    b_clc_done = Column(Integer, server_default=text("'-1'"))
    n_reads_target = Column(Integer, server_default=text("'-1'"))
    cdhit_good_library = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_otu_target = Column(Float(asdecimal=True), server_default=text("'-1'"))
    cdhit_good_library_target = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_singleton_target = Column(Float(asdecimal=True), server_default=text("'-1'"))
    blast_singleton = Column(Float(asdecimal=True), server_default=text("'-1'"))
    update_type = Column(Enum(u'once', u'year'), server_default=text("'once'"))
    update_count = Column(Integer, server_default=text("'0'"))
    comm_ver = Column(Float(asdecimal=True), server_default=text("'0'"))
    primer_set = Column(Integer)
    db_info = Column(String(100))
    blast_good_library = Column(Float(asdecimal=True))
    blast_good_library_target = Column(Float(asdecimal=True))


class TblCg(Base):
    __tablename__ = 'tbl_cg'

    uid = Column(Integer, primary_key=True)
    f_order_uid = Column(Integer, index=True, server_default=text("'-1'"))
    f_sample_id = Column(String(10), server_default=text("''"))
    f_completion_date = Column(DateTime, index=True, server_default=text("CURRENT_TIMESTAMP"))
    f_sample_guids = Column(Text)
    f_sample_numbers = Column(String(10))
    f_download = Column(Text)
    f_download_old = Column(Text)
    f_my_comment = Column(Text)
    f_admin_comment = Column(Text)
    user_group_uid = Column(Integer, server_default=text("'-1'"))
    user_uid = Column(Integer, server_default=text("'-1'"))
    share_user_uid = Column(String(500), server_default=text("'-1'"))


class TblGenome(Base):
    __tablename__ = 'tbl_genome'

    uid = Column(Integer, primary_key=True)
    f_order_uid = Column(Integer, index=True, server_default=text("'-1'"))
    f_sample_id = Column(String(10), index=True, server_default=text("''"))
    f_completion_date = Column(DateTime, index=True, server_default=text("CURRENT_TIMESTAMP"))
    f_species = Column(String(100), server_default=text("''"))
    f_strain = Column(String(50), server_default=text("''"))
    f_contigs = Column(Integer)
    f_size = Column(Integer)
    f_download = Column(Text)
    f_download_old = Column(Text)
    f_my_comment = Column(Text)
    f_admin_comment = Column(Text)
    user_group_uid = Column(Integer, server_default=text("'-1'"))
    user_uid = Column(Integer, server_default=text("'-1'"))
    share_user_uid = Column(String(500), server_default=text("'-1'"))


class TblMc(Base):
    __tablename__ = 'tbl_mc'

    uid = Column(Integer, primary_key=True)
    f_order_uid = Column(Integer, index=True, server_default=text("'-1'"))
    f_run_id = Column(String(100), index=True)
    n_samples = Column(Integer)
    f_completion_date = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"))
    f_download = Column(Text)
    f_summary = Column(Text)
    f_my_comment = Column(Text)
    f_admin_comment = Column(Text)
    user_uid = Column(Integer)
    share_user_uid = Column(String(500))


class TblRnaseq(Base):
    __tablename__ = 'tbl_rnaseq'
    __table_args__ = (
        Index('f_order_uid_f_sample_id', 'f_order_uid', 'f_sample_id', unique=True),
    )

    uid = Column(Integer, primary_key=True)
    f_order_uid = Column(Integer, index=True, server_default=text("'-1'"))
    f_sample_id = Column(String(50), index=True, server_default=text("''"))
    f_completion_date = Column(DateTime, index=True, server_default=text("CURRENT_TIMESTAMP"))
    f_sample_name = Column(String(50), server_default=text("''"))
    f_reference_id = Column(String(50), server_default=text("''"))
    f_reference_name = Column(String(200), server_default=text("''"))
    f_download = Column(Text)
    f_download_old = Column(Text)
    f_my_comment = Column(Text)
    f_analysis_name = Column(String(256))
    f_admin_comment = Column(Text)
    user_group_uid = Column(Integer, server_default=text("'-1'"))
    user_uid = Column(Integer, server_default=text("'-1'"))
    share_user_uid = Column(String(500), server_default=text("'-1'"))
